### PR TITLE
Correct path to CSS in readme

### PR DESCRIPTION
**Pull request by backspace**
Hey, small documentation fix here. Thanks for making this!

### CODE REVIEW

**Comment by mgwalker** [comment]
Whoops!  Thanks for this.

**Comment by backspace** [comment]
No problem! Maybe it’s omgtoosoon to use this, I was wondering? In my project, I [needed some extra CSS to get it working](https://github.com/backspace/adventure-registrations/blob/primary/web/static/css/app.scss#L71-L81); specifically, I needed to set an explicit width and height and scale the background. I could make additional PRs to document that, or maybe this isn’t meant for public consumption yet and I got a supersecret advance preview in the Slack? haha

**Comment by mgwalker** [comment]
Hmm!  Let me look into that - they should default to `1em` (and also I need to go look up what a `rem` is!).  The very first line of the generated CSS is:

```
.fa{display:inline-block;width:1em;height:1em;background-size:contain;}
```

As for being public-ready...  I don't know!  lol.  Having never put together something that people might actually want to use (outside of work), I don't really know how to deem it "ready."  There are several things I want to investigate to make it easier to use, but I feel like it ought to be _nearly_ ready for actual use.  For what it's worth, I'm planning on rolling it into a site I maintain for a small non-profit.

**Comment by backspace** [comment]
oooh you know, I was having a CSS crisis where weird Javascript was inserted into the concatenated CSS. I have since fixed that and I get proper sizing when I remove my `.fa`-related rules! So disregard. Thanks. It does seem ready to use.

**Comment by mgwalker** [comment]
Sweet!  The biggest issue I have with widespread use is just the problem of coloring them however you want.  With Font-Awesome, it's easy: you set the `color` style because it's just a font.  Bit different here, though.

**Pull request merged**
